<template>
  <!-- <div class="about"> -->
    <b-container fluid id="terms">
        <b-row class="text-center">
            <b-col class="p-3">
              <h2 class="page-title">Terms of Use</h2>
            </b-col>
        </b-row>
        <row>
          <col  cols="6" md="auto">
            <hr></hr>
          </col>
        </row>
        <b-row class="text-center">
            <b-col class="p-3" md="6" offset-md="3">
            <p> AT INSIGHT SUPPLY, WE DO OUR BEST TO PROVIDE EDUCATIONAL AND INFORMATIONAL CONTENT TO A VERY WIDE AUDIENCE, BUT YOUR USE OF OUR SERVICES IS AT YOUR SOLE RISK. WE PROVIDE THESE SERVICES ON AN "AS IS" AND "AS AVAILABLE" BASIS, AND WE EXPRESSLY DISCLAIM ALL EXPRESS OR IMPLIED WARRANTIES OF ALL KINDS, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTY THAT OUR SERVICES WILL MEET YOUR REQUIREMENTS, BE SAFE, SECURE, UNINTERRUPTED, TIMELY, ACCURATE, OR ERROR-FREE, OR THAT YOUR INFORMATION WILL BE SECURE.</p>

            <p>WE ARE NOT RESPONSIBLE FOR THE CONTENT, DATA, OR ACTIONS OF THIRD PARTIES, AND YOU RELEASE US, OUR DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS FROM ANY CLAIMS AND DAMAGES, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH ANY CLAIM YOU HAVE AGAINST ANY SUCH THIRD PARTIES. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US OR THROUGH OR FROM OUR SERVICES CREATES ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS OF USE.</p>

            <p>ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH YOUR USE OF OUR SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. YOU AGREE THAT WE HAVE NO RESPONSIBILITY OR LIABILITY FOR THE DELETION OF, OR THE FAILURE TO STORE OR TO TRANSMIT, ANY CONTENT OR COMMUNICATION MAINTAINED BY THE SERVICE. WE RETAIN THE RIGHT TO CREATE LIMITS ON USE AND STORAGE AT OUR SOLE DISCRETION AT ANY TIME WITH OR WITHOUT NOTICE.
            </p>
            </b-col>
        </b-row>
    </b-container>
  <!-- </div> -->
</template>
<script>
export default {
  name: 'terms',
  components: {

  },
  props: {},
  data: function(){
    return {

    }
  }
}

</script>
<style scoped type="scss">
@import "../scss/utilities/_variables.scss";
p {
  font-size: .75rem;
}
</style>