# Generated by Django 2.1.3 on 2018-12-26 01:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import notes.models


class Migration(migrations.Migration):

    replaces = [('notes', '0001_initial'), ('notes', '0002_auto_20181223_0146'), ('notes', '0003_remove_insight_approved'), ('notes', '0004_auto_20181223_1524'), ('notes', '0005_auto_20181223_1541'), ('notes', '0006_auto_20181223_1601')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('color', models.CharField(default='#FFFFFF', max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('source_url', models.TextField(max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=notes.models.get_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.Category')),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
